import Vue from 'vue'
import MasterPage from './shared/MasterPage.vue';
import RelatorioPage from './shared/RelatorioPage.vue';
import CadastroUsuario from './administracao/usuario/Cadastro.vue';
import ListaUsuario from './administracao/usuarios/usuario/ListaUsuario.vue';
import ListaPermissao from './administracao/usuarios/permissao/ListaPermissao.vue';
import Auditoria from './administracao/usuarios/auditoria/Auditoria.vue';
import MeusDados from './administracao/usuario/MeusDados.vue';
import CadastroAssinante from './administracao/assinante/Cadastro.vue' ;
import DadosAssinante from './administracao/assinante/DadosAssinante.vue';
import CadastroIndice from '@/components/vendas/indice/Cadastro.vue'; 
import CadastroTipoIndice from '@/components/vendas/tipoindice/Cadastro.vue'; 
import CadastroEmpresa from './negocios/empresa/Cadastro.vue';
import CadastroPessoa from '@/components/negocios/pessoa/Cadastro.vue';
//import DetalharPessoa from '@/components/vendas/contrato/visualizar/VisualizarPessoa.vue';
import NovoEmpreendimento from "@/components/negocios/empreendimento/Cadastro.vue";
//import ListaMultiLotes from '@/components/negocios/empreendimento/ListaMultiLotes.vue';
import Unidade from "@/components/negocios/empreendimento/VisualizarUnidade.vue";
import LadosAdicionais from "@/components/negocios/empreendimento/LadosAdicionais.vue";
import GerarGrupos from "@/components/negocios/empreendimento/GerarGrupos.vue";
import TipoProcessoJudicial from "@/components/vendas/tipoprocesso/Cadastro.vue";
import ObservacaoInput from "@/components/shared/AdicionarObservacao.vue";
import EnderecoInput from "@/components/shared/Endereco.vue";
import MoneyInput from "@/components/shared/MoneyInput.vue";
import DocumentCard from "@/components/shared/DocumentCard.vue";
import AdicionarLotes from "@/components/shared/AdicionarLote.vue";
import VCardDocumento from "@/components/shared/AdicionarDocumento.vue";
import ValoresAdicionaisReceita from "@/components/shared/ValoresAdicionais.vue";
import VCardHistorico from "@/components/shared/Historico.vue";
import VcardManutencao from "@/components/shared/Manutencao.vue";
import VCardContato from "@/components/shared/AdicionarContato.vue";

/* REGUA */
import CadastroContaGerencial from "./financeiro/classificacao/contagerencial/Cadastro.vue";
import CadastroCentroCusto from "./financeiro/classificacao/centrocusto/Cadastro.vue";
import CadastroBanco from "./financeiro/banco/Cadastro.vue";
import CadastroTipoDocumento from "./financeiro/tipodocumento/Cadastro.vue";
import CadastroRetornoBancario from "./financeiro/retornobancario/Cadastro.vue";
import CadastroRemessa from "./financeiro/remessa/Cadastro.vue";
import CadastroFormaPagamento from "./financeiro/formapagamento/Cadastro.vue";
import CadastroDespesa from "./financeiro/despesa/Cadastro.vue";
import CadastroReceita from "./financeiro/receita/Cadastro.vue";
import ParcelaBaixa from "./financeiro/despesa/ParcelaBaixa.vue";
import ParcelaBaixaReceita from "./financeiro/receita/ParcelaBaixa.vue";
import DetalharDespesa from "./financeiro/despesa/DetalharDespesa.vue";
import ParcelaDetalheReceita from "./financeiro/receita/ParcelaDetalhe.vue";
import EditarParcela from "./financeiro/receita/EditarParcela.vue";
import EditarParcelaDespesa from "./financeiro/despesa/EditarParcela.vue";
import GerenciarParcelasDespesa from "./financeiro/despesa/GerenciarParcelas.vue";
import GerenciadorReceita from "@/components/financeiro/receita/GerenciadorReceita.vue";
import GerenciadorReceitaPrice from "@/components/financeiro/receita/GerenciadorReceitaPrice.vue";
import ValoresAdicionais from "@/components/financeiro/receita/ValoresAdicionais.vue";
import CadastroParametroContrato from "./administracao/parametrizacao/Cadastro.vue";
import CadastroTipoServicoReceita from "./financeiro/tiposervicoreceita/Cadastro.vue";
import AgruparAntecipar from "@/components/vendas/contrato/acoes/Agrupar.vue";
import QuitadorContrato from "@/components/vendas/contrato/acoes/Quitar.vue";
import Simular from "@/components/vendas/contrato/acoes/SimularAmortizacao.vue";
import ConfigurarReceita from "@/components/vendas/contrato/acoes/Configurar.vue";
import AjusteAmortizacao from "@/components/vendas/contrato/parcela/ReajustarValor.vue";
import SplitPagamento from "@/components/vendas/contrato/parcela/SplitPagamento.vue";
import EditarParcelaManual from "@/components/vendas/contrato/parcela/Editar.vue";
import AtualizarDataSequencia from "@/components/vendas/contrato/parcela/ReajustarData.vue";
import AnteciparContrato from "@/components/vendas/contrato/parcela/Antecipar.vue";
import BaixasRetroativa from "@/components/vendas/contrato/parcela/BaixaRetroativa.vue";
import AgruparParcela from "@/components/vendas/contrato/parcela/Agrupar.vue";
import EmpreendimentoContrato from "@/components/vendas/contrato/visualizar/VisualizarEmpreendimento.vue";
import DespesaContratual from "@/components/vendas/contrato/acoes/ReceitaServico.vue";
import EncargosDescontos from "@/components/vendas/contrato/acoes/EncargoFinanceiro.vue";
import NovoCadastroContrato from "@/components/vendas/contrato/Cadastro.vue";
import AtalhoFiltro from "@/components/vendas/contrato/Atalho.vue";
import Aditar from "@/components/vendas/contrato/Aditar.vue";
import DetalharContrato from "@/components/vendas/contrato/visualizar/VisualizarContrato.vue";
import GerenciadorContrato from "@/components/vendas/contrato/Gerenciar.vue";
import VisualizarContrato from "./vendas/contrato/Visualizar.vue";
import VisualizarMultiplosLotes from "./vendas/contrato/Visualizar.vue";
import CadastroSignatario from "@/components/vendas/signatario/Cadastro.vue";
import CadastroTipoContrato from "@/components/vendas/tipocontrato/Cadastro.vue";
import InfoPlanoPagamento from "@/components/negocios/empreendimento/VisualizarPlano.vue";

Vue.component("plano-pagamento-info", InfoPlanoPagamento);



/*SPLIT*/
import CadastroTransferencia from "./financeiro/transferencia/Cadastro.vue";

Vue.component("cadastro-transferencia", CadastroTransferencia);

  
Vue.component('atalho-filtro', AtalhoFiltro);
Vue.component('visualizar-contrato', VisualizarContrato);
Vue.component('visualizar-multiplosLotes', VisualizarMultiplosLotes);
Vue.component('dados-assinante', DadosAssinante);
Vue.component('cadastro-assinante', CadastroAssinante);
Vue.component('cadastro-usuario', CadastroUsuario);
Vue.component('vcardusuario', ListaUsuario);
Vue.component('vcardpermissao', ListaPermissao);
Vue.component('vcardauditoria', Auditoria);
Vue.component('meus-dados', MeusDados)
Vue.component('novo-cadastro-contrato', NovoCadastroContrato);  
Vue.component('detalhar-contrato', DetalharContrato);
Vue.component('encargos-descontos', EncargosDescontos);
Vue.component('empreendimento-contrato', EmpreendimentoContrato);
Vue.component('master-page', MasterPage);
Vue.component('relatorio-page', RelatorioPage);
Vue.component('cadastro-banco', CadastroBanco);
Vue.component('cadastro-centrocusto', CadastroCentroCusto);
Vue.component('cadastro-contagerencial', CadastroContaGerencial);
Vue.component('cadastro-tipoprocessojudicial', TipoProcessoJudicial);
Vue.component('novo-empreendimento', NovoEmpreendimento);
//Vue.component('lista-multilotes', ListaMultiLotes);
Vue.component("visualizar-unidade", Unidade);
Vue.component("lados-adicionais", LadosAdicionais);
Vue.component("gerar-grupos", GerarGrupos);

Vue.component("cadastro-tipodocumento", CadastroTipoDocumento);
Vue.component("cadastro-retornobancario", CadastroRetornoBancario);
Vue.component("cadastro-remessa", CadastroRemessa);
Vue.component("cadastro-formapagamento", CadastroFormaPagamento);
Vue.component("cadastro-despesa", CadastroDespesa);
Vue.component("cadastro-receita", CadastroReceita);
Vue.component("editar-parcela", EditarParcela);
Vue.component("gerenciar-parcelas-despesa", GerenciarParcelasDespesa);
Vue.component("editar-parcelaDespesa", EditarParcelaDespesa);
Vue.component("parcelabaixa-despesa", ParcelaBaixa);
Vue.component("parcelabaixa-receita", ParcelaBaixaReceita);
Vue.component("detalhar-despesa", DetalharDespesa);
Vue.component("parceladetalhe-receita", ParcelaDetalheReceita);
Vue.component("cadastro-tiposervicoreceita", CadastroTipoServicoReceita);
Vue.component("cadastro-parametro-contrato", CadastroParametroContrato);
Vue.component("cadastro-empresa", CadastroEmpresa);
Vue.component("cadastro-indice", CadastroIndice);
Vue.component("cadastro-tipoindice", CadastroTipoIndice);
Vue.component("cadastro-pessoa", CadastroPessoa);
//Vue.component('detalhar-pessoa', DetalharPessoa)
Vue.component("gerenciador-receitaprice", GerenciadorReceitaPrice);
Vue.component("gerenciador-receita", GerenciadorReceita);
Vue.component("valores-adicionais", ValoresAdicionais);
Vue.component("gerenciador-contrato", GerenciadorContrato);
Vue.component("vcard-endereco", EnderecoInput);
Vue.component("money-input", MoneyInput);
Vue.component("document-card", DocumentCard);
Vue.component("multi-lotes", AdicionarLotes);
Vue.component("vcard-observacao", ObservacaoInput);
Vue.component("vcard-historico", VCardHistorico);
Vue.component("vcard-manutencao", VcardManutencao);
Vue.component("vcard-contato", VCardContato);
Vue.component("vcard-documento", VCardDocumento);
Vue.component("valores-adicionaisreceita", ValoresAdicionaisReceita);
Vue.component("cadastro-signatario", CadastroSignatario);
Vue.component("cadastro-tipocontrato", CadastroTipoContrato);
Vue.component("aditar-contrato", Aditar);
Vue.component("quitador-contrato", QuitadorContrato);
Vue.component("antecipar-contrato", AnteciparContrato);
Vue.component("baixas-retroativa", BaixasRetroativa);
Vue.component("despesa-contratual", DespesaContratual);
Vue.component("agrupar-parcela", AgruparParcela);
Vue.component("atualizar-dataSequencia", AtualizarDataSequencia);
Vue.component("editar-parcelaManual", EditarParcelaManual);
Vue.component("ajuste-amortizacao", AjusteAmortizacao);
Vue.component("split-pagamento", SplitPagamento);
Vue.component("agrupar-antecipar", AgruparAntecipar);
Vue.component("configurar-receita", ConfigurarReceita);
Vue.component("simular-parcela", Simular);
